name: ci

on:
  push:
    branches:
      - "release/v1.14"

jobs:
  DockerPublish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Determine version
        run: |
          VERSION=$(cat nginx/static/version.json | jq -r '.version')$($(cat nginx/static/version.json | jq -r '.pre_release') && echo "a" || :)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/masz_backend:latest
            ghcr.io/${{ github.repository_owner }}/masz_backend:${{ env.VERSION }}

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: nginx
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/masz_nginx:latest
            ghcr.io/${{ github.repository_owner }}/masz_nginx:${{ env.VERSION }}
